name: Tests

on: [push]

env:
  CACHE_NUMBER: 0  # increase to reset cache manually
  
jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    steps:
    
    - uses: actions/checkout@v3
    - name: Set up Python 3.11.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.11.9'
        
    - name: Set cache date
      run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

    - name: Install package and requirements
      run: |
        python3 -m pip install -e ".[dev]"
        python3 -m pip install Cython==0.29.37
        python3 -m pip install pyqg==0.7.2 --no-build-isolation --use-deprecated=legacy-resolver

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Test with pytest
      run: |
        python -m pytest
